services:
  - type: web
    name: control-tablillas
    env: python
    buildCommand: pip install -r requirements_compatible.txt
    startCommand: streamlit run app_original.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    # Updated: 2024 - Clean repository configuration